import { Inter } from 'next/font/google'
import './css/globals.css'
import Head from 'next/head'
import Header from './components/header'
import Footer from './components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"/>
      </head>
      <body className={inter.className}>
        <section className='main_sec'>
          <Header/>
        </section>
        <main>
        {children}
        </main>
        <Footer/>
      </body>
    </html>
  )
}
